<!-- Mario Uceda Yeves
Lenguaje de Marcas // Desarrollo de Aplicaciones Multiplataforma (DAM)
Fecha de entrega: 2019-02-15 // Fecha oficial de entrega: 2019-02-15-->

<!DOCTYPE aeropuertos [
<!ELEMENT aeropuertos (aeropuerto*)>
<!ELEMENT aeropuerto (nombre,cerrado?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cerrado EMPTY>
]>

<aeropuertos>
    <aeropuerto>
        <nombre> Berlín Schönefeld (SFX)</nombre>
    </aeropuerto>
    <aeropuerto>
        <nombre> Berlín Tempelhof (THF)</nombre>
        <cerrado />
    </aeropuerto>
</aeropuertos>